// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Templaty.PostgresStoreSample.Persistence;

#nullable disable

namespace Templaty.PostgresStoreSample.Persistence.Migrations.Develop
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710212257_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Templaty.Postgres.Content", b =>
                {
                    b.Property<string>("Path")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Path");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("contents", (string)null);

                    b.HasData(
                        new
                        {
                            Path = "Templates_HelloWorld",
                            Body = "Hello world!"
                        },
                        new
                        {
                            Path = "Templates_Hello",
                            Body = "Hello {{name}} {{second_name}}!"
                        },
                        new
                        {
                            Path = "Notifications_WheaterDistributionTemplate",
                            Body = "Date: {{date}}\nTemperature: {{temperature}} °C\nSummary: {{summary}}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
